package it.unicas.project.template.address.model.dao;

import java.util.List;

/**
 * The Data Access Object (DAO) Interface defines the standard contract
 * for all data access classes in the application.
 * <p>
 * This interface is generic, allowing it to be implemented by DAOs that
 * handle different model entities (e.g., User, Material, Loan).
 * </p>
 *
 * @param <T> The type of the domain model object the DAO handles.
 */
public interface DAO<T> {

    /**
     * Retrieves a list of objects of type T from the persistence layer
     * based on criteria specified in the input object.
     * <p>
     * This method supports dynamic queries where non-default fields in the
     * input object 'a' are used to filter the results (e.g., search by name, ID).
     * </p>
     *
     * @param a The object containing the criteria (template) for the selection.
     * @return A list of objects matching the criteria.
     * @throws DAOException if a database error occurs.
     */
    List<T> select(T a) throws DAOException;

    /**
     * Updates an existing object of type T in the persistence layer.
     * <p>
     * The input object 'a' must contain a valid ID to identify the record
     * to be modified.
     * </p>
     *
     * @param a The object containing the updated data.
     * @throws DAOException if a database error occurs or the object is invalid.
     */
    void update(T a) throws DAOException;

    /**
     * Inserts a new object of type T into the persistence layer.
     * <p>
     * The object 'a' should not have its primary key set (as it is usually
     * auto-generated by the database). The DAO implementation is typically
     * responsible for retrieving and setting the generated ID on the object 'a'.
     * </p>
     *
     * @param a The object to be persisted.
     * @throws DAOException if a database error occurs or the object is invalid.
     */
    void insert(T a) throws DAOException;

    /**
     * Deletes an object of type T from the persistence layer.
     * <p>
     * The input object 'a' must contain a valid ID to identify the record
     * to be removed.
     * </p>
     *
     * @param a The object to be deleted.
     * @throws DAOException if a database error occurs or the ID is missing.
     */
    void delete(T a) throws DAOException;

    /**
     * Retrieves all objects of type T from the persistence layer.
     * <p>
     * This is a simple query equivalent to selecting all rows from the
     * corresponding table, often implemented by calling {@code select(null)}.
     * </p>
     *
     * @return A list of all objects of type T.
     * @throws DAOException if a database error occurs.
     */
    List<T> selectAll() throws DAOException;
}